{ defaultPackage ? null }:
{
  config,
  lib,
  pkgs,
  ...
}:

let
  cfg = config.services.stave;

  # Only non-secret values are exposed to the browser. Credentials are entered
  # in-app and stored locally on the client — never served from the host.
  publicConfig = lib.filterAttrs (_: v: v != null) {
    server = cfg.server;
    username = cfg.username;
    instanceName = cfg.instanceName;
  };

  configJs = pkgs.writeText "config.js" ''
    // Generated by the NixOS module (services.stave).
    // Contains public defaults only: no credentials are ever served.
    window.__STAVE_CONFIG__ = ${builtins.toJSON publicConfig};
  '';

  root = pkgs.runCommand "stave-root" { } ''
    cp -r ${cfg.package} $out
    chmod -R u+w $out
    cp ${configJs} $out/config.js
  '';
in
{
  options.services.stave = {
    enable = lib.mkEnableOption "the stave web app";

    package = lib.mkOption {
      type = lib.types.package;
      default = defaultPackage;
      defaultText = lib.literalExpression "stave.packages.\${system}.default";
      description = "The built stave SPA to serve.";
    };

    hostName = lib.mkOption {
      type = lib.types.str;
      default = "localhost";
      example = "music.example.org";
      description = "Virtual host the app is served on.";
    };

    server = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      example = "https://navidrome.example.org";
      description = ''
        Subsonic server URL to pre-fill in the app's login form.
        Public information only — this value is served to every browser.
      '';
    };

    username = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Username to pre-fill in the login form (never a password).";
    };

    instanceName = lib.mkOption {
      type = lib.types.nullOr lib.types.str;
      default = null;
      description = "Label shown in the app's header instead of the default name.";
    };

    openFirewall = lib.mkOption {
      type = lib.types.bool;
      default = false;
      description = "Open ports 80/443 in the firewall.";
    };

    extraNginxConfig = lib.mkOption {
      type = lib.types.attrsOf (lib.types.submodule { freeformType = lib.types.attrs; });
      default = { };
      description = "Extra nginx locations merged into the virtual host.";
    };
  };

  config = lib.mkIf cfg.enable {
    assertions = [
      {
        assertion = cfg.package != null;
        message = ''
          services.stave.package is unset. Either use the flake's
          nixosModule (which provides a default) or set it explicitly, e.g.
          services.stave.package = inputs.stave.packages.''${pkgs.stdenv.hostPlatform.system}.default;
        '';
      }
    ];

    services.nginx.enable = lib.mkDefault true;
    services.nginx.virtualHosts.${cfg.hostName} = {
      root = "${root}";
      locations = {
        "/" = {
          tryFiles = "$uri $uri/ /index.html";
          extraConfig = ''
            add_header Cache-Control "no-cache";
          '';
        };
        "/assets/" = {
          extraConfig = ''
            expires 1y;
            add_header Cache-Control "public, immutable";
          '';
        };
        "= /sw.js" = {
          extraConfig = ''
            add_header Cache-Control "no-cache";
          '';
        };
        "= /config.js" = {
          extraConfig = ''
            add_header Cache-Control "no-cache";
          '';
        };
      }
      // cfg.extraNginxConfig;
    };

    networking.firewall.allowedTCPPorts = lib.mkIf cfg.openFirewall [
      80
      443
    ];
  };
}
