#!/usr/bin/env bash
#
# Create a release keystore, then patch android/app/build.gradle with a default
# versionCode/versionName only if absent. Both grader steps are idempotent.
#
# Usage:
#   scripts/android-keystore.sh /path/to/release.jks
#
# Writes android/keystore.properties (git-ignored) pointing at the keystore, so a
# plain `just android-release` afterwards produces a *signed* app-release.apk.
#
# The keystore is the app's identity: keep it somewhere safe and back it up. Losing
# it means you can never update an installed copy — Android rejects an update
# signed with a different key. Losing its *password* is the same as losing it.
set -euo pipefail

KEYSTORE="${1:-}"
if [ -z "$KEYSTORE" ]; then
  echo "usage: scripts/android-keystore.sh /path/to/release.jks" >&2
  exit 2
fi

REPO="$(git rev-parse --show-toplevel)"
PROPS="$REPO/android/keystore.properties"
ALIAS="${ANDROID_KEY_ALIAS:-stave}"

if ! command -v keytool >/dev/null 2>&1; then
  echo "keytool not found — run this from the dev shell (nix develop)" >&2
  exit 127
fi

if [ -e "$KEYSTORE" ]; then
  echo "keystore already exists at $KEYSTORE — leaving it alone"
else
  echo "creating a release keystore at $KEYSTORE (valid 10000 days)"
  # -storepass / -keypass are prompted interactively on purpose: a password on the
  # command line ends up in your shell history and in `ps` output.
  keytool -genkeypair \
    -keystore "$KEYSTORE" \
    -alias "$ALIAS" \
    -keyalg RSA -keysize 4096 \
    -validity 10000 \
    -dname "CN=stave, OU=release, O=stave, L=, ST=, C="
fi

cat >"$PROPS" <<EOF
# Generated by scripts/android-keystore.sh — git-ignored, never commit this.
# Relative paths are resolved against android/app, so ../ is the android/ dir.
storeFile=$(realpath "$KEYSTORE")
storePassword=CHANGE_ME
keyAlias=$ALIAS
keyPassword=CHANGE_ME
EOF

echo
echo "wrote $PROPS"
echo "Now put the real passwords in it (the prompt values you just typed), then:"
echo "  just android-release     # -> android/app/build/outputs/apk/release/app-release.apk"
echo
echo "Or keep them out of the file entirely and export them instead:"
echo "  ANDROID_KEYSTORE_PATH=$KEYSTORE ANDROID_KEYSTORE_PASSWORD=… ANDROID_KEY_ALIAS=$ALIAS ANDROID_KEY_PASSWORD=… just android-release"
