#!/usr/bin/env bash
#
# Declare the foreground-service permission the media session needs.
#
# `android/` is generated by `cap add android` / `cap sync` and is git-ignored, so
# this cannot be a hand edit to the manifest: a regeneration would silently drop it
# and the media service would throw SecurityException the moment the user presses
# play, on a device, after a release.
#
# @capgo/capacitor-media-session declares its own MediaSessionService and the
# FOREGROUND_SERVICE permission, but not FOREGROUND_SERVICE_MEDIA_PLAYBACK — which
# is mandatory for an app targeting API 34+ (Capacitor 8 targets 36) that starts a
# `mediaPlayback` service. Without it there is no notification and, because the
# service never starts, Android suspends the WebView and kills playback in the
# background.
#
# Run by the android recipes; idempotent.
set -euo pipefail

REPO="$(git rev-parse --show-toplevel)"
MANIFEST="$REPO/android/app/src/main/AndroidManifest.xml"
PERMISSION="android.permission.FOREGROUND_SERVICE_MEDIA_PLAYBACK"

if [ ! -f "$MANIFEST" ]; then
  echo "android/app/src/main/AndroidManifest.xml not found — run 'pnpm exec cap add android' first" >&2
  exit 1
fi

if grep -qF "$PERMISSION" "$MANIFEST"; then
  echo "foreground service permission already declared"
  exit 0
fi

before="$(grep -c 'uses-permission' "$MANIFEST" || true)"
sed -i "s|</manifest>|    <uses-permission android:name=\"$PERMISSION\" />\n</manifest>|" "$MANIFEST"
after="$(grep -c 'uses-permission' "$MANIFEST" || true)"

# Check that the edit landed instead of trusting that sed exited 0 — a permission
# that was never added only fails at runtime, on a device, after a release.
if [ "$after" -le "$before" ]; then
  echo "failed to add $PERMISSION to AndroidManifest.xml" >&2
  exit 1
fi

echo "declared $PERMISSION in AndroidManifest.xml"
