#!/usr/bin/env node
// Bump the version in every place that records it.
//
//   node scripts/bump-version.mjs 0.2.0
//
// package.json is the single source of truth: flake.nix reads it directly, so
// the Nix package, the web app and the Android build all stay in step.
// Android's versionCode is derived as major*10000 + minor*100 + patch.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const next = process.argv[2];

if (!next) {
  console.error('usage: bump-version.mjs <version>   e.g. bump-version.mjs 0.2.0');
  process.exit(1);
}

const parsed = /^(\d+)\.(\d+)\.(\d+)(?:-[0-9A-Za-z.-]+)?$/.exec(next);
if (!parsed) {
  console.error(`not a valid semver version: ${next}`);
  process.exit(1);
}
const [, major, minor, patch] = parsed;
const versionCode = Number(major) * 10000 + Number(minor) * 100 + Number(patch);

const pkgPath = resolve(root, 'package.json');
const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
const previous = pkg.version;
pkg.version = next;
writeFileSync(pkgPath, `${JSON.stringify(pkg, null, 2)}\n`);
console.log(`package.json          ${previous} -> ${next}`);

// Android: gradle files are generated by `cap add android`, so tolerate absence.
const gradlePath = resolve(root, 'android/app/build.gradle');
if (existsSync(gradlePath)) {
  let gradle = readFileSync(gradlePath, 'utf8');
  const before = gradle;
  gradle = gradle
    .replace(/versionCode \d+/, `versionCode ${versionCode}`)
    .replace(/versionName "[^"]*"/, `versionName "${next}"`);
  if (gradle !== before) {
    writeFileSync(gradlePath, gradle);
    console.log(`android/app/build.gradle  versionName -> ${next} (code ${versionCode})`);
  } else {
    console.log('android/app/build.gradle  no versionName/versionCode found — skipped');
  }
} else {
  console.log('android/ not present — skipped (run `just android-sync` to generate it)');
}

const capPath = resolve(root, 'capacitor.config.ts');
if (existsSync(capPath)) {
  console.log(`capacitor.config.ts   appId unchanged (versionName comes from gradle)`);
}

console.log(`\nversion ${next} (android versionCode ${versionCode})`);
console.log('next: just release ' + next);
