#!/usr/bin/env bash
# Run a throwaway Navidrome instance against a local library, for developing
# and manually testing stave against the real reference server.
#
#   dev-navidrome.sh [MUSIC_DIR] [DATA_DIR]
#
# Env: PORT (4533), ND_USER (admin), ND_PASS (admin)
#
# The instance is disposable: everything lives under DATA_DIR (default
# devdata/navidrome), so deleting that folder resets the server completely.

set -euo pipefail

MUSIC_DIR="${1:-testdata/music}"
DATA_DIR="${2:-devdata/navidrome}"
PORT="${PORT:-4533}"
NUSER="${ND_USER:-admin}"
NPASS="${ND_PASS:-admin}"

MUSIC_DIR="$(readlink -f "$MUSIC_DIR")"
if [ ! -d "$MUSIC_DIR" ]; then
  echo "music folder not found: $MUSIC_DIR" >&2
  echo "run: just seed-library   (or nix run .#seed-library -- $MUSIC_DIR)" >&2
  exit 1
fi

mkdir -p "$DATA_DIR"
DATA_DIR="$(readlink -f "$DATA_DIR")"
CONFIG="$DATA_DIR/navidrome.toml"
DB="$DATA_DIR/data/navidrome.db"

cat > "$CONFIG" <<EOF
# Generated by stave dev-navidrome.sh — throwaway config.
#
# The scan interval is deliberately NOT set: Navidrome 0.64 ignores every
# config-file spelling of it (ScanInterval, ScanSchedule, Scanner.Interval),
# warns about it, and falls back to its own default. Leaving it out keeps the
# logs clean.
MusicFolder = "$MUSIC_DIR"
DataFolder = "$DATA_DIR/data"
CacheFolder = "$DATA_DIR/cache"
Address = "127.0.0.1"
Port = $PORT
EnableInsightsCollector = false
LogLevel = "info"
EOF

# `navidrome user list` prints a CSV with a header row: id,username,...
user_exists() {
  navidrome --nobanner --configfile "$CONFIG" user list 2>/dev/null |
    awk -F, -v u="$NUSER" 'NR > 1 && $2 == u { found = 1 } END { exit !found }'
}

if [ ! -f "$DB" ] || ! user_exists; then
  echo "==> creating dev user '$NUSER'"
  # `navidrome user create` prompts for the password and needs a TTY, so the
  # password is fed through `script`, which allocates a pty for the child.
  if printf '%s\n%s\n' "$NPASS" "$NPASS" |
    script -qec "navidrome --nobanner --configfile '$CONFIG' user create -u '$NUSER' --name 'Dev Admin' --admin" /dev/null \
      > "$DATA_DIR/user-create.log" 2>&1; then
    echo "==> user '$NUSER' ready (password: $NPASS)"
  else
    echo "note: automatic user creation failed — see $DATA_DIR/user-create.log" >&2
    echo "      create it by hand with:" >&2
    echo "      ND_CONFIGFILE=$CONFIG navidrome user create -u $NUSER --admin" >&2
  fi
fi

echo "==> navidrome on http://127.0.0.1:$PORT  (user: $NUSER / $NPASS)"
echo "    Subsonic API: http://127.0.0.1:$PORT/rest"
echo "    data: $DATA_DIR   (delete it to start over)"
echo "    integration tests: just interop"
echo

exec navidrome --nobanner --configfile "$CONFIG"
