#!/usr/bin/env bash
# Regenerate the royalty-free demo library used for local development, the
# mock server, the e2e suite and manual QA.
#
# Everything is synthesised with ffmpeg: no third-party audio is bundled, so the
# library is licence-free and deterministic (same input -> same output).
#
# Usage: seed-library.sh [OUT_DIR]

set -euo pipefail

OUT_DIR="${1:-testdata/music}"
FILES_ONLY="${SEED_FILES_ONLY:-0}"

if [ "$FILES_ONLY" != "1" ]; then
  rm -rf "$OUT_DIR"
fi
mkdir -p "$OUT_DIR"

# --- catalog ----------------------------------------------------------------
# "Artist|Album|Year|Genre|Tracks|BaseHz|CoverFrom|CoverTo"
CATALOG=(
  "Aurelia Vance|Neon Cartography|2021|Ambient|5|196|0x1b2a4a|0xff8c42"
  "Aurelia Vance|Static Bloom|2023|Ambient|4|220|0x2a1b4a|0x35d0d0"
  "Bit Rot Orchestra|Terminal Velocity|2019|Electronic|6|262|0x4a1b2a|0xc96fd8"
  "Bit Rot Orchestra|Checksum Faults|2024|Electronic|5|294|0x1b4a2a|0x7fb069"
  "Corvid Choir|Winter Transmissions|2017|Folk|5|330|0x3a2f1b|0xffb454"
  "Delta Queue|Backpressure|2022|Jazz|6|175|0x1b3a44|0x6a9ec4"
  "Delta Queue|Idempotent Nights|2025|Jazz|4|165|0x2b2b2b|0xd8e0dc"
  "Empty Set|Null Pointers|2020|Post-Rock|5|147|0x241b3a|0xb07fd8"
)

# Track titles are generated from a small word pool with a fixed seed so that
# repeated runs produce identical libraries.
# Word pools for track titles. They are read through a nameref (`local -n` in
# `word_at`), which shellcheck cannot follow, so it reports them as unused.
# shellcheck disable=SC2034
WORDS_A=(glass circuit hollow amber static velvet binary dusk iron paper
  quiet radiant sodium tessel rust mirror cobalt drift ember lattice
  copper neon marble frozen silt arcade horizon gravel cipher)
# shellcheck disable=SC2034
WORDS_B=(theorem drift signal lattice fracture murmur sequence aperture cascade
  interval vestige parallax nocturne threshold vacancy iterance solstice
  gradient alphabet refraction afterimage)

# Deterministic word selection.
#
# NOTE: the callers use `$(…)`, i.e. a subshell, so this must not rely on
# mutating shell state (an LCG here would reset on every call and give every
# track the same title). Deriving the index arithmetically keeps titles varied
# *and* reproducible.
word_at() {
  local -n pool="$1"
  local index="$2"
  echo "${pool[$(( index % ${#pool[@]} ))]}"
}

track_index=0
album_count=0

for entry in "${CATALOG[@]}"; do
  IFS='|' read -r artist album year genre tracks base_hz cover_a cover_b <<< "$entry"
  album_count=$((album_count + 1))
  album_dir="$OUT_DIR/$artist/$album ($year)"
  mkdir -p "$album_dir"

  # Cover art: a deterministic two-colour gradient, attached to every track.
  # NOTE: no `speed=` here — ffmpeg 6 (what Ubuntu ships) rejects speed=0 as out
  # of range while newer ffmpeg tolerates it. The default speed renders the same
  # frame 0, so leaving it out is both portable and unchanged output.
  ffmpeg -loglevel error -y \
    -f lavfi -i "gradients=s=600x600:c0=$cover_a:c1=$cover_b:d=1" \
    -frames:v 1 "$album_dir/cover.png"

  for ((t = 1; t <= tracks; t++)); do
    track_index=$((track_index + 1))
    wa=$(word_at WORDS_A $(( album_count * 7 + t * 3 )))
    wb=$(word_at WORDS_B $(( album_count * 11 + t * 5 )))
    title="$wa $wb"
    # Slight per-track pitch movement so the audio is not one long tone.
    freq=$(( base_hz + (t - 1) * 7 + (album_count * 3) ))
    dur=$(( 18 + (track_index % 12) ))
    fmt="mp3"
    # Every fourth album gets a lossless track, to exercise codec handling.
    if [ $((album_count % 4)) -eq 0 ] && [ "$t" -eq 1 ]; then fmt="flac"; fi

    track_no=$(printf "%02d" "$t")
    out="$album_dir/$track_no - $title.$fmt"

    common=(
      -metadata "title=$title"
      -metadata "artist=$artist"
      -metadata "album=$album"
      -metadata "albumartist=$artist"
      -metadata "track=$t/$tracks"
      -metadata "disc=1"
      -metadata "date=$year"
      -metadata "genre=$genre"
      -metadata "comment=Generated by stave seed-library (public domain)"
    )

    if [ "$fmt" = "flac" ]; then
      ffmpeg -loglevel error -y \
        -f lavfi -i "sine=frequency=$freq:duration=$dur:sample_rate=44100" \
        -i "$album_dir/cover.png" \
        -map 0:a -map 1:v -c:v copy -disposition:v attached_pic \
        "${common[@]}" -c:a flac "$out"
    else
      ffmpeg -loglevel error -y \
        -f lavfi -i "sine=frequency=$freq:duration=$dur:sample_rate=44100" \
        -i "$album_dir/cover.png" \
        -map 0:a -map 1:v -c:v copy -disposition:v attached_pic \
        "${common[@]}" -c:a libmp3lame -q:a 6 "$out"
    fi
  done

  # Keep one folder-level cover and a playlist, like a real library.
  mv "$album_dir/cover.png" "$album_dir/folder.png"
  echo "  $artist / $album ($year): $tracks tracks"
done

# A couple of loose "singles" with no album, to exercise the singles path.
mkdir -p "$OUT_DIR/Loose Tracks"
for i in 1 2 3; do
  ffmpeg -loglevel error -y \
    -f lavfi -i "sine=frequency=$(( 300 + i * 40 )):duration=15:sample_rate=44100" \
    -metadata "title=Loose Signal $i" \
    -metadata "artist=Various" \
    -metadata "genre=Compilation" \
    -metadata "date=2026" \
    -c:a libmp3lame -q:a 6 "$OUT_DIR/Loose Tracks/Loose Signal $i.mp3"
done

echo
echo "Seeded $(find "$OUT_DIR" -type f \( -name '*.mp3' -o -name '*.flac' \) | wc -l) tracks across $album_count albums in $OUT_DIR"
echo "Navidrome needs a rescan to pick them up if it is already running."
